######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 30 22:45:15 2011
######################################################################

TEMPLATE = app
QT += core
QT -= gui

# Directories
DESTDIR = ./build
MOC_DIR = ./build
OBJECTS_DIR = ./build

SOURCES += \
    src/main.cpp \
    src/Portfolio.cpp \
    src/Market.cpp

HEADERS += \
    src/Portfolio.h \
    src/Market.h
